---
- name: Deploy Application Containers
  hosts: worker1
  tasks:
    - name: Pull Docker image
      docker_image:
        name: dimitrij118/docker_nodejs

    - name: Deploy Container 1
      docker_container:
        name: container_one
        image: dimitrij118/docker_nodejs
        ports:
          - "5000:4000"
        env:
          PORT: "4000"

    - name: Deploy Container 2
      docker_container:
        name: container_two
        image: dimitrij118/docker_nodejs
        ports:
          - "6000:4000"
        env:
          PORT: "4000"
