---
- hosts: worker1
  tasks:
    - name: Pull Docker image
      docker_image:
        name: "dimitrij118/docker_nodejs"
        source: pull

    - name: Run Docker container 1
      docker_container:
        name: nodejs_app_1
        image: "dimitrij118/docker_nodejs"
        ports: "5000:{{ PORT }}"
      env:
        PORT: "{{ PORT }}"
        DATA_TEXT: "{{ DATA_TEXT }}"

    - name: Run Docker container 2
      docker_container:
        name: nodejs_app_2
        image: "dimitrij118/docker_nodejs"
        ports: "6000:{{ PORT }}"
      env:
        PORT: "{{ PORT }}"
        DATA_TEXT: "{{ DATA_TEXT }}"
        volume:
