- hosts: worker1
  tasks:
    - name: Install openssl-server package
      when: ansible_facts['distribution'] == 'Ubuntu'
      apt:
        name: openssl-server
        state: present
      become: true
