- hosts: worker1
  tasks:
    - name: Create new_testdir directory
      file:
        path: /home/user/new_testdir
        state: directory
        mode: "u=rwx,g=rx,o="

    - name: Create and set permissions for new_file.txt
      copy:
        content: "Some text"
        dest: /home/user/new_testdir/new_file.txt
        mode: "u=--x,g=rw,o=rwx"
