- hosts: EU-west
  tasks:
    - name: Golang
      get_url:
        url: "https://storage.googleapis.com/golang/go1.17.1.linux-amd64.tar.gz"
        dest: /tmp/go1.17.1.linux-amd64.tar.gz

    - name: Extract Golang
      unarchive:
        src: /tmp/go1.17.1.linux-amd64.tar.gz
        dest: /usr/local
